# Generated by Django 5.1.2 on 2024-11-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('rollno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=30)),
            ],
        ),
    ]
