# Generated by Django 5.1.2 on 2024-11-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('eventID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('eventStart', models.DateTimeField()),
                ('eventEnd', models.DateTimeField()),
                ('deptID', models.CharField(max_length=20)),
                ('organizer', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('type_of_event', models.CharField(max_length=20)),
                ('eventGallery', models.TextField(blank=True, null=True)),
                ('registration_link', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
