# Generated by Django 5.1.2 on 2024-11-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_delete_eventregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentPersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('deptID', models.CharField(max_length=20)),
                ('phnNo', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('personalMail', models.EmailField(max_length=254)),
                ('section', models.CharField(max_length=10)),
                ('date_of_joining', models.DateField()),
                ('fathername', models.CharField(max_length=100)),
                ('mothername', models.CharField(max_length=100)),
                ('fatherphn', models.CharField(max_length=15)),
                ('motherphn', models.CharField(max_length=15)),
                ('father_occupation', models.CharField(max_length=100)),
                ('mother_occupation', models.CharField(max_length=100)),
                ('fatherEducation', models.CharField(max_length=50)),
                ('motherEducation', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('hostel_or_dayScholar', models.CharField(max_length=20)),
                ('collegeBus', models.CharField(max_length=10)),
                ('aadharNo', models.CharField(max_length=20)),
                ('fee_reimbursement', models.CharField(max_length=10)),
            ],
        ),
    ]
